### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by avico78** [ClimenteA/fastapi-mongo-caddy2-vue-react-svelte#1]
Looke interesting, but i dont see any integration between front end to fastapi,are u planning to continue working on this ?

**Comment by ClimenteA** [comment]
You can call the endpoints from FastAPI in the front end. 

You can work separately on the frontend and the backend. When you are ready with the front end generate the `dist` folder and place it in the backend. You can let FastAPI to deliver the static files. 

Now I'm working on a task queue alternative to redis RQ (checkout kerground). I'm planning to make this boilerplate production ready, but I didn't set a deadline.

**Comment by avico78** [comment]
Thanks @ClimenteA , i think such idea could be really good starting point for beginners , but i guess it required more information ,especially for "how to" start building a project with fastapi/Vue.
